services:
  sml-api-paperless:
    build: .
    container_name: sml-api-bybos-paperless
    ports:
      - "${HOST_PORT:-8201}:${SERVER_PORT:-8201}"
    env_file:
      - .env
    restart: unless-stopped
