package handlers

import "strings"

type transFlagCatalogEntry struct {
	MenuCode string
	NameTH   string
	NameEN   string
	Table    string
	Type     int
}

var transFlagCatalog = map[int]transFlagCatalogEntry{
	0:    {MenuCode: "10.2.1", NameTH: "ข้อมูลรายวัน", NameEN: "Daily Information", Table: "gl_journal", Type: 1},
	2:    {MenuCode: "3.1", NameTH: "บันทึกใบเสนอซื้อ", NameEN: "Purchase Requisition", Table: "ic_trans", Type: 1},
	3:    {MenuCode: "3.3.1", NameTH: "ยกเลิกใบเสนอซื้อ", NameEN: "Cancel Purchase requisition", Table: "ic_trans", Type: 1},
	4:    {MenuCode: "3.2", NameTH: "อนุมัติใบเสนอซื้อ", NameEN: "Approve Requistion", Table: "ic_trans", Type: 1},
	6:    {MenuCode: "3.4", NameTH: "บันทึกใบสั่งซื้อ", NameEN: "Purchase Order", Table: "ic_trans", Type: 1},
	7:    {MenuCode: "3.6.1", NameTH: "ยกเลิกใบสั่งซื้อ", NameEN: "Cancel Purchase Order", Table: "ic_trans", Type: 1},
	8:    {MenuCode: "3.5", NameTH: "อนุมัติใบสั่งซื้อ", NameEN: "Approve Purchase Order", Table: "ic_trans", Type: 1},
	10:   {MenuCode: "3.8", NameTH: "จ่ายเงินล่วงหน้า", NameEN: "Advance Payment", Table: "ic_trans", Type: 1},
	11:   {MenuCode: "3.12", NameTH: "จ่ายเงินมัดจำ", NameEN: "Payment Deposit", Table: "ic_trans", Type: 1},
	12:   {MenuCode: "3.15", NameTH: "ซื้อสินค้า", NameEN: "Purchases order", Table: "ic_trans", Type: 1},
	13:   {MenuCode: "3.19.1", NameTH: "ยกเลิกซื้อสินค้า", NameEN: "Cancel Purchases order", Table: "ic_trans", Type: 1},
	14:   {MenuCode: "3.16", NameTH: "เพิ่มหนี้เจ้าหนี้,เพิ่มสินค้า", NameEN: "Increased Debt (AP), Additional Products", Table: "ic_trans", Type: 1},
	15:   {MenuCode: "3.19.3", NameTH: "ยกเลิกซื้อเพิ่มสินค้า/เพิ่มหนี้", NameEN: "Cancel Purchase Add/Debt Increase", Table: "ic_trans", Type: 1},
	16:   {MenuCode: "3.17", NameTH: "ลดหนี้เจ้าหนี้, ลดสินค้า", NameEN: "Debit note AP, Return Goods", Table: "ic_trans", Type: 1},
	17:   {MenuCode: "3.19.2", NameTH: "ยกเลิกส่งคืนสินค้า/ลดหนี้", NameEN: "Cancel Return/Credit Note", Table: "ic_trans", Type: 1},
	19:   {MenuCode: "5.12", NameTH: "จ่ายชำระหนี้(เจ้าหนี้)", NameEN: "Payments (AP)", Table: "ap_ar_trans", Type: 1},
	20:   {MenuCode: "3.9", NameTH: "รับคืนเงินล่วงหน้า", NameEN: "Return of Receive Earnest Special", Table: "ic_trans", Type: 1},
	23:   {MenuCode: "5.13.2", NameTH: "ยกเลิกจ่ายชำระหนี้(เจ้าหนี้)", NameEN: "Cancel Payments", Table: "ap_ar_trans", Type: 1},
	25:   {MenuCode: "3.13", NameTH: "รับคืนเงินมัดจำ", NameEN: "Deposit Payment Return", Table: "ic_trans", Type: 1},
	30:   {MenuCode: "4.1", NameTH: "บันทึกใบเสนอราคา", NameEN: "Sale Quotation", Table: "ic_trans", Type: 2},
	31:   {MenuCode: "4.3.1", NameTH: "ยกเลิกใบเสนอราคา", NameEN: "Cancel Sales Quotation", Table: "ic_trans", Type: 2},
	32:   {MenuCode: "4.2", NameTH: "อนุมัติใบเสนอราคา", NameEN: "Approve Quotation", Table: "ic_trans", Type: 2},
	34:   {MenuCode: "4.4", NameTH: "บันทึกใบสั่งซื้อ/สั่งจอง", NameEN: "Purchase Order/Booking", Table: "ic_trans", Type: 2},
	36:   {MenuCode: "4.7", NameTH: "บันทึกใบสั่งขาย", NameEN: "Sale Order Record", Table: "ic_trans", Type: 2},
	37:   {MenuCode: "4.9.1", NameTH: "ยกเลิกใบสั่งขาย", NameEN: "Cancel Sales Order", Table: "ic_trans", Type: 2},
	38:   {MenuCode: "4.5", NameTH: "อนุมัติใบสั่งซื้อ/สั่งจอง", NameEN: "Approve Purchase Order/Inquiry Order", Table: "ic_trans", Type: 2},
	39:   {MenuCode: "4.6.1", NameTH: "ยกเลิกใบสั่งซื้อ/สั่งจอง", NameEN: "Cancel Purchase Order / Sales Reserve", Table: "ic_trans", Type: 2},
	40:   {MenuCode: "4.11", NameTH: "รับเงินล่วงหน้า", NameEN: "Receive Earnest Special", Table: "ic_trans", Type: 2},
	41:   {MenuCode: "4.13.1", NameTH: "ยกเลิกรับเงินล่วงหน้า", NameEN: "Cancel AR. Earnest", Table: "ic_trans", Type: 2},
	42:   {MenuCode: "4.12", NameTH: "คืนเงินล่วงหน้า", NameEN: "Prepayment Return", Table: "ic_trans", Type: 2},
	43:   {MenuCode: "4.13.2", NameTH: "ยกเลิกคืนเงินล่วงหน้า", NameEN: "Cancel Prepayment Return", Table: "ic_trans", Type: 2},
	44:   {MenuCode: "4.18", NameTH: "ขายสินค้า/บริการ", NameEN: "Sales and Service", Table: "ic_trans", Type: 2},
	45:   {MenuCode: "4.22.1", NameTH: "ยกเลิกขายสินค้า/บริการ", NameEN: "Cancel Sale/Service", Table: "ic_trans", Type: 2},
	46:   {MenuCode: "4.2", NameTH: "เพิ่มหนี้", NameEN: "Debit Note", Table: "ic_trans", Type: 2},
	47:   {MenuCode: "4.22.3", NameTH: "ยกเลิกขายเพิ่มสินค้า/เพิ่มหนี้", NameEN: "Cancel Invoice Add /Debt Increase", Table: "ic_trans", Type: 2},
	48:   {MenuCode: "4.19", NameTH: "รับคืนคืนสินค้า/ลดหนี้", NameEN: "Credit Note", Table: "ic_trans", Type: 2},
	49:   {MenuCode: "4.22.2", NameTH: "ยกเลิกรับคืนสินค้า/ลดหนี้", NameEN: "Cancel Returned/Refund Cr. Note", Table: "ic_trans", Type: 2},
	52:   {MenuCode: "4.8", NameTH: "อนุมัติใบสั่งขาย", NameEN: "Approve Sale Order", Table: "ic_trans", Type: 2},
	54:   {MenuCode: "2.11", NameTH: "สินค้า/วัตถุดิบ คงเหลือยกมา", NameEN: "Stock Balance Forward", Table: "ic_trans", Type: 3},
	56:   {MenuCode: "2.14", NameTH: "เบิกสินค้า/วัตถุดิบ", NameEN: "Material/Goods Issue", Table: "ic_trans", Type: 3},
	57:   {MenuCode: "2.16.3", NameTH: "ยกเลิกใบเบิกสินค้า/วัตถุดิบ", NameEN: "Cancel Product issue/Material", Table: "ic_trans", Type: 3},
	58:   {MenuCode: "2.15", NameTH: "รับคืนสินค้า/วัตถุดิบ จากการเบิก", NameEN: "Receive Return of goods from Issue", Table: "ic_trans", Type: 3},
	59:   {MenuCode: "2.16.4", NameTH: "ยกเลิกรับคืนสินค้า/วัตถุดิบจากการเบิก", NameEN: "Cancel Return Product/Material From Issue", Table: "ic_trans", Type: 3},
	60:   {MenuCode: "2.12", NameTH: "รับสินค้าสำเร็จรูป", NameEN: "Finish Goods Receive", Table: "ic_trans", Type: 3},
	61:   {MenuCode: "2.16.1", NameTH: "ยกเลิกรับสินค้าสำเร็จรูป", NameEN: "Cancel Finish Product", Table: "ic_trans", Type: 3},
	66:   {MenuCode: "2.20", NameTH: "ปรับปรุงสต๊อกสินค้า/วัตถุดิบ (เกิน)", NameEN: "Stock Adjustment (Increase)", Table: "ic_trans", Type: 3},
	67:   {MenuCode: "2.22.2", NameTH: "ยกเลิกปรับปรุงสต๊อกสินค้า/วัตถุดิบ (เกิน)", NameEN: "Cancel Adjust Stk/Over", Table: "ic_trans", Type: 3},
	68:   {MenuCode: "2.21", NameTH: "ปรับปรุงสต๊อกสินค้า/วัตถุดิบ (ขาด)", NameEN: "Stock Adjustment (Decrease)", Table: "ic_trans", Type: 3},
	69:   {MenuCode: "2.22.3", NameTH: "ยกเลิกปรับปรุงสต๊อกสินค้า/วัตถุดิบ (ขาด)", NameEN: "Cancel Adjust Stk/Lost", Table: "ic_trans", Type: 3},
	70:   {MenuCode: "2.18", NameTH: "โอนสินค้า/วัตถุดิบ [เข้า]", NameEN: "Transfer Goods/Raw material (IN)", Table: "ic_trans", Type: 3},
	72:   {MenuCode: "2.18", NameTH: "โอนสินค้า/วัตถุดิบ [ออก]", NameEN: "Transfer Goods/Raw material (OUT)", Table: "ic_trans", Type: 3},
	73:   {MenuCode: "2.22.1", NameTH: "ยกเลิกโอนสินค้า/วัตถุดิบ", NameEN: "Cancel Transfer WH Out", Table: "ic_trans", Type: 3},
	76:   {MenuCode: "2.19.2", NameTH: "ตรวจนับสินค้า", NameEN: "Check Stock", Table: "ic_trans", Type: 3},
	81:   {MenuCode: "5.2", NameTH: "ตั้งหนี้ยกมา(เจ้าหนี้)", NameEN: "Bring Forward IR.(AP)", Table: "ic_trans", Type: 4},
	83:   {MenuCode: "5.4", NameTH: "เพิ่มหนี้ยกมา(เจ้าหนี้)", NameEN: "Dedit Note Balance brought forward (AP)", Table: "ic_trans", Type: 4},
	85:   {MenuCode: "5.3", NameTH: "ลดหนี้ยกมา(เจ้าหนี้)", NameEN: "Credit Note Balance brought forward (AP)", Table: "ic_trans", Type: 4},
	87:   {MenuCode: "5.7", NameTH: "ตั้งหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Other IR.(AP)", Table: "ic_trans", Type: 1},
	88:   {MenuCode: "5.10.1", NameTH: "ยกเลิกตั้งหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Cancel Other IR.(AP)", Table: "ic_trans", Type: 1},
	89:   {MenuCode: "5.9", NameTH: "เพิ่มหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Other Debit (AP)", Table: "ic_trans", Type: 1},
	90:   {MenuCode: "5.10.3", NameTH: "ยกเลิกเพิ่มหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Cancel Other Debit Increase(AP)", Table: "ic_trans", Type: 1},
	91:   {MenuCode: "5.8", NameTH: "ลดหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Other Debt (AP)", Table: "ic_trans", Type: 1},
	92:   {MenuCode: "5.10.2", NameTH: "ยกเลิกลดหนี้อื่นๆ(เจ้าหนี้)", NameEN: "Cancel Other Income Decrease (AP)", Table: "ic_trans", Type: 1},
	93:   {MenuCode: "6.2", NameTH: "ตั้งหนี้ยกมา(ลูกหนี้)", NameEN: "Bring Forward IR.(AR)", Table: "ic_trans", Type: 5},
	95:   {MenuCode: "6.3", NameTH: "เพิ่มหนี้ยกมา(ลูกหนี้)", NameEN: "Dedit Note Balance brought forward (AR)", Table: "ic_trans", Type: 5},
	97:   {MenuCode: "6.3", NameTH: "ลดหนี้ยกมา(ลูกหนี้)", NameEN: "Credit Note Balance brought forward (AR)", Table: "ic_trans", Type: 5},
	99:   {MenuCode: "6.6", NameTH: "ตั้งหนี้อื่นๆ(ลูกหนี้)", NameEN: "Other IR.(AR)", Table: "ic_trans", Type: 2},
	100:  {MenuCode: "6.9.1", NameTH: "ยกเลิกตั้งหนี้อื่นๆ(ลูกหนี้)", NameEN: "Cancel Other IR.(AR)", Table: "ic_trans", Type: 2},
	101:  {MenuCode: "6.7", NameTH: "เพิ่มหนี้อื่นๆ(ลูกหนี้)", NameEN: "Other Debit (AR)", Table: "ic_trans", Type: 2},
	102:  {MenuCode: "6.9.8", NameTH: "ยกเลิกเพิ่มหนี้อื่นๆ(ลูกหนี้)", NameEN: "Cancel Other Debit Increase(AR)", Table: "ic_trans", Type: 2},
	103:  {MenuCode: "6.8", NameTH: "ลดหนี้อื่นๆ(ลูกหนี้)", NameEN: "Other Debt (AR)", Table: "ic_trans", Type: 2},
	104:  {MenuCode: "6.9.2", NameTH: "ยกเลิกลดหนี้อื่นๆ(ลูกหนี้)", NameEN: "Cancel Other Income Decrease (AR)", Table: "ic_trans", Type: 2},
	110:  {MenuCode: "4.15", NameTH: "รับเงินมัดจำ", NameEN: "Deposit Receipt", Table: "ic_trans", Type: 2},
	111:  {MenuCode: "4.17.1", NameTH: "ยกเลิกรับเงินมัดจำ", NameEN: "Cancel Receive Debit", Table: "ic_trans", Type: 2},
	112:  {MenuCode: "4.16", NameTH: "คืนเงินมัดจำ", NameEN: "Refund Deposit", Table: "ic_trans", Type: 2},
	113:  {MenuCode: "4.17.2", NameTH: "ยกเลิกคืนเงินมัดจำ", NameEN: "Cancel Deposit Return", Table: "ic_trans", Type: 2},
	122:  {MenuCode: "2.13", NameTH: "ขอเบิกสินค้า/วัตถุดิบ", NameEN: "Stock Issue Request", Table: "ic_trans", Type: 3},
	123:  {MenuCode: "2.16.2", NameTH: "ยกเลิกขอเบิกสินค้า/วัตถุดิบ", NameEN: "Stock Issue Request Cancel", Table: "ic_trans", Type: 3},
	124:  {MenuCode: "2.17", NameTH: "ขอโอนสินค้า/วัตถุดิบ", NameEN: "Stock Transfer Request", Table: "ic_trans", Type: 3},
	150:  {MenuCode: "3.10.1", NameTH: "ยกเลิกจ่ายเงินล่วงหน้า", NameEN: "Cancel Prepayment", Table: "ic_trans", Type: 1},
	151:  {MenuCode: "3.14.1", NameTH: "ยกเลิกจ่ายเงินมัดจำ", NameEN: "Cancel Payment Deposit", Table: "ic_trans", Type: 1},
	152:  {MenuCode: "4.17.2", NameTH: "ยกเลิกรับคืนเงินมัดจำ", NameEN: "Cancel Deposit Return", Table: "ic_trans", Type: 1},
	161:  {MenuCode: "4.13.2", NameTH: "ยกเลิกรับคืนเงินล่วงหน้า", NameEN: "Cancel Return of Receive Earnest Special", Table: "ic_trans", Type: 1},
	213:  {MenuCode: "5.11", NameTH: "ใบรับวางบิล(เจ้าหนี้)", NameEN: "Billing receipt (AP)", Table: "ap_ar_trans", Type: 1},
	214:  {MenuCode: "5.13.1", NameTH: "ยกเลิกใบรับวางบิล(เจ้าหนี้)", NameEN: "Cancel Billing receipt (AP)", Table: "ap_ar_trans", Type: 1},
	235:  {MenuCode: "6.10", NameTH: "ใบวางบิล (ลูกหนี้)", NameEN: "Invoice (Account Payable)", Table: "ap_ar_trans", Type: 2},
	236:  {MenuCode: "6.12.1", NameTH: "ยกเลิกใบวางบิล(ลูกหนี้)", NameEN: "Cancel Pay bill", Table: "ap_ar_trans", Type: 2},
	239:  {MenuCode: "6.11", NameTH: "รับชำระหนี้/ออกใบเสร็จรับเงิน", NameEN: "Payment/Receipt", Table: "ap_ar_trans", Type: 2},
	240:  {MenuCode: "6.12.2", NameTH: "ยกเลิกชำระหนี้/ยกเลิกใบเสร็จรับเงิน", NameEN: "Cancel Debt Billing/Cancel Receipt", Table: "ap_ar_trans", Type: 2},
	250:  {MenuCode: "7.1", NameTH: "รายได้อื่น ๆ", NameEN: "Other income", Table: "ic_trans", Type: 2},
	251:  {MenuCode: "7.4.1", NameTH: "ยกเลิกรายได้อื่น ๆ", NameEN: "Cancel other revenue", Table: "ic_trans", Type: 2},
	252:  {MenuCode: "7.2", NameTH: "ลดหนี้รายได้อื่น ๆ", NameEN: "Decrease Debt Other Income", Table: "ic_trans", Type: 2},
	253:  {MenuCode: "7.4.2", NameTH: "ยกเลิกลดหนี้รายได้อื่น ๆ", NameEN: "Cancel debt reduction of other revenue", Table: "ic_trans", Type: 2},
	254:  {MenuCode: "7.3", NameTH: "เพิ่มหนี้รายได้อื่น ๆ", NameEN: "Add debt,other revenue", Table: "ic_trans", Type: 2},
	255:  {MenuCode: "7.4.3", NameTH: "ยกเลิกเพิ่มหนี้รายได้อื่น ๆ", NameEN: "Other income increased debt cancellation.", Table: "ic_trans", Type: 2},
	260:  {MenuCode: "7.5", NameTH: "ค่าใช้จ่ายอื่น ๆ", NameEN: "Other Expense", Table: "ic_trans", Type: 2},
	261:  {MenuCode: "7.8.1", NameTH: "ยกเลิกค่าใช้จ่ายอื่น ๆ", NameEN: "Cancel other charges", Table: "ic_trans", Type: 2},
	262:  {MenuCode: "7.6", NameTH: "ลดหนี้ค่าใช้จ่ายอื่น ๆ", NameEN: "Decrease Other Expense", Table: "ic_trans", Type: 2},
	263:  {MenuCode: "7.8.2", NameTH: "ยกเลิกลดหนี้ค่าใช้จ่ายอื่น ๆ", NameEN: "Cancel reduce debt other charges", Table: "ic_trans", Type: 2},
	264:  {MenuCode: "7.7", NameTH: "เพิ่มหนี้ค่าใช้จ่ายอื่น ๆ", NameEN: "Expense Other Debt", Table: "ic_trans", Type: 2},
	265:  {MenuCode: "7.8.3", NameTH: "ยกเลิกเพิ่มหนี้ค่าใช้จ่ายอื่น ๆ", NameEN: "Increased debt cancellation charges on.", Table: "ic_trans", Type: 2},
	301:  {MenuCode: "7.9.3", NameTH: "บันทึกรับเงินสดย่อย", NameEN: "Petty Cash Return", Table: "ic_trans", Type: 2},
	302:  {MenuCode: "7.9.4.1", NameTH: "ยกเลิกขอเบิกเงินสดย่อย", NameEN: "Cancel Cash Request", Table: "ic_trans", Type: 2},
	303:  {MenuCode: "7.9.4.2", NameTH: "ยกเลิกรับคืนเงินสดย่อย", NameEN: "Cancel Cash Request", Table: "ic_trans", Type: 2},
	310:  {MenuCode: "3.18.1", NameTH: "รับสินค้าแบบพาเชียล", NameEN: "Partial_Recieve product", Table: "ic_trans", Type: 1},
	311:  {MenuCode: "3.18.2", NameTH: "ส่งคืน/ราคาผิด", NameEN: "Partial_Produce return or wrong price", Table: "ic_trans", Type: 1},
	315:  {MenuCode: "3.18.3", NameTH: "ตั้งหนี้", NameEN: "Partial_Increase Debt", Table: "ic_trans", Type: 1},
	316:  {MenuCode: "3.18.4", NameTH: "เพิ่มหนี้", NameEN: "Partial_Add debt", Table: "ic_trans", Type: 1},
	317:  {MenuCode: "3.18.5", NameTH: "ลดหนี้ ทยอยรับ", NameEN: "Partial_Credit Note", Table: "ic_trans", Type: 1},
	330:  {MenuCode: "3.18.6", NameTH: "ยกเลิกรับสินค้า", NameEN: "Goods Receipt Cancel", Table: "ic_trans", Type: 1},
	331:  {MenuCode: "3.18.7", NameTH: "ยกเลิกส่งคืนสินค้า/ราคาผิด", NameEN: "Cancel Return/Credit Note", Table: "ic_trans", Type: 1},
	335:  {MenuCode: "3.18.8", NameTH: "ยกเลิกตั้งหนี้จากการรับสินค้า", NameEN: "Cancel Receive from Purchase/Receipt Invoice", Table: "ic_trans", Type: 1},
	336:  {MenuCode: "3.18.10", NameTH: "ยกเลิกเพิ่มหนี้จากใบตั้งหนี้", NameEN: "Cancel Receive from Purchase/Receipt Add", Table: "ic_trans", Type: 1},
	337:  {MenuCode: "3.18.9", NameTH: "ยกเลิกลดหนี้จากใบตั้งหนี้", NameEN: "Cancel Receive from Receipt Credit Note", Table: "ic_trans", Type: 1},
	401:  {MenuCode: "7.10.1.3", NameTH: "บันทึกฝากเงิน", NameEN: "Payin Cash Record", Table: "ic_trans", Type: 2},
	402:  {MenuCode: "7.10.1.4", NameTH: "บันทึกถอนเงิน", NameEN: "Withdraw Record", Table: "ic_trans", Type: 2},
	403:  {MenuCode: "7.10.1.6.1", NameTH: "บันทึกยกเลิกฝากเงิน", NameEN: "Cancel Payin Record", Table: "ic_trans", Type: 2},
	404:  {MenuCode: "7.10.1.6.2", NameTH: "บันทึกยกเลิกถอนเงิน", NameEN: "Withdraw cancel record", Table: "ic_trans", Type: 2},
	405:  {MenuCode: "7.10.2.1", NameTH: "เช็ครับยกมา", NameEN: "Cheque Received Balance", Table: "ic_trans", Type: 2},
	406:  {MenuCode: "7.10.3.1", NameTH: "เช็คจ่ายยกมา", NameEN: "Payment Cheque Balance", Table: "ic_trans", Type: 1},
	410:  {MenuCode: "7.10.2.3", NameTH: "บันทึกนำฝากเช็ครับ", NameEN: "Payin (Cheque Received)", Table: "ic_trans", Type: 2},
	411:  {MenuCode: "7.10.2.4", NameTH: "บันทึกเช็ครับผ่าน", NameEN: "Recieve cheqe pass", Table: "ic_trans", Type: 2},
	412:  {MenuCode: "7.10.2.5", NameTH: "บันทึกเช็ครับคืน", NameEN: "Cheque Return (Received)", Table: "ic_trans", Type: 2},
	413:  {MenuCode: "7.10.9.3", NameTH: "บันทึกยกเลิกเช็ครับ", NameEN: "Cheque Cancel Record", Table: "ic_trans", Type: 2},
	416:  {MenuCode: "7.10.2.7", NameTH: "บันทึกเปลี่ยนเช็ครับ", NameEN: "Renew Cheque (Received)", Table: "ic_trans", Type: 2},
	420:  {MenuCode: "7.10.1.5", NameTH: "บันทึกโอนเงินระหว่างธนาคาร [เข้า]", NameEN: "Transfer Between Bank", Table: "ic_trans", Type: 0},
	422:  {MenuCode: "7.10.1.5", NameTH: "บันทึกโอนเงินระหว่างธนาคาร [ออก]", NameEN: "Transfer Between Bank", Table: "ic_trans", Type: 0},
	423:  {MenuCode: "7.10.1.6.1", NameTH: "บันทึกยกเลิกเงินโอนเข้า", NameEN: "Cancel Transfer Between Bank", Table: "ic_trans", Type: 2},
	430:  {MenuCode: "7.10.2.9.1", NameTH: "บันทึกยกเลิกนำฝากเช็ครับ", NameEN: "Cancel Chq Pay In Record", Table: "ic_trans", Type: 2},
	431:  {MenuCode: "7.10.2.9.2", NameTH: "บันทึกยกเลิกเช็ครับผ่าน", NameEN: "Recieve cheqe pass", Table: "ic_trans", Type: 2},
	432:  {MenuCode: "7.10.2.9.3", NameTH: "บันทึกยกเลิกเช็ครับคืน", NameEN: "Cheque Cancel Record", Table: "ic_trans", Type: 2},
	433:  {MenuCode: "7.10.2.9.4", NameTH: "บันทึกยกเลิกเช็ครับยกเลิก", NameEN: "Cancel the canceled checks", Table: "ic_trans", Type: 2},
	436:  {MenuCode: "7.10.2.9.5", NameTH: "บันทึกยกเลิกเปลี่ยนเช็คนำฝาก", NameEN: "Cancel Cheque Change", Table: "ic_trans", Type: 2},
	451:  {MenuCode: "7.10.3.3", NameTH: "บันทึกเช็คจ่ายผ่าน", NameEN: "Payment cheque", Table: "ic_trans", Type: 1},
	452:  {MenuCode: "7.10.3.7.1", NameTH: "บันทึกเช็คจ่ายยกเลิก", NameEN: "Cheque Cancel Record (Payment)", Table: "ic_trans", Type: 1},
	453:  {MenuCode: "7.10.3.4", NameTH: "บันทึกเช็คจ่ายคืน", NameEN: "Repay cheque", Table: "ic_trans", Type: 1},
	456:  {MenuCode: "7.10.3.6", NameTH: "บันทึกเปลี่ยนเช็คจ่าย", NameEN: "Cheque Change (Payment)", Table: "ic_trans", Type: 1},
	461:  {MenuCode: "7.10.4.2", NameTH: "บันทึกขั้นเงินบัตรเครดิต", NameEN: "By credit card", Table: "ic_trans", Type: 2},
	462:  {MenuCode: "7.10.4.3", NameTH: "บันทึกยกเลิกบัตรเครดิต", NameEN: "Cancel Credit Record", Table: "ic_trans", Type: 2},
	471:  {MenuCode: "7.10.3.3", NameTH: "บันทึกยกเลิกเช็คจ่ายผ่าน", NameEN: "Cheque Cancel Record", Table: "ic_trans", Type: 1},
	472:  {MenuCode: "7.10.3.7.1", NameTH: "บันทึกยกเลิกเช็คจ่ายยกเลิก", NameEN: "Canceled checks paid Cancel", Table: "ic_trans", Type: 1},
	473:  {MenuCode: "7.10.3.7.3", NameTH: "บันทึกยกเลิกเช็คจ่ายคืน", NameEN: "Cancel repay cheqe", Table: "ic_trans", Type: 1},
	476:  {MenuCode: "7.10.3.7.4", NameTH: "บันทึกยกเลิกเปลี่ยนเช็คจ่าย", NameEN: "Cancel Cheque Change (Payment)", Table: "ic_trans", Type: 1},
	801:  {MenuCode: "7.1.5", NameTH: "แต้มคงเหลือยกมา", NameEN: "Points accumulated", Table: "ic_trans", Type: 0},
	802:  {MenuCode: "7.1.6", NameTH: "บันทึกตัดแต้ม", NameEN: "Use Points", Table: "ic_trans", Type: 0},
	1801: {MenuCode: "8.7", NameTH: "โอนข้อมูลเข้าสู่ระบบบัญชี", NameEN: "Transfers Account System", Table: "as_trans", Type: 0},
	1998: {MenuCode: "9.9", NameTH: "ประมวลผลสิ้นงวด", NameEN: "Year Process", Table: "gl_journal", Type: 0},
	1999: {MenuCode: "9.10", NameTH: "ประมวลผลสิ้นปี", NameEN: "Yesr Process", Table: "gl_journal", Type: 0},
}

func lookupTransFlagCatalog(transFlag int, table string) (transFlagCatalogEntry, bool) {
	entry, ok := transFlagCatalog[transFlag]
	if !ok {
		return transFlagCatalogEntry{}, false
	}
	if entry.Table != "" && table != "" && !strings.EqualFold(entry.Table, table) {
		return transFlagCatalogEntry{}, false
	}
	return entry, true
}
